apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mailrules
  name: mailrules
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailrules
  template:
    metadata:
      labels:
        app: mailrules
    spec:
      containers:
      - name: mailrules
        image: us-south1-docker.pkg.dev/homelab-388417/homelab/mailrules:latest
        imagePullPolicy: Always
        env:
          - name: MAILRULES_USERNAME
            valueFrom:
              secretKeyRef:
                name: mailrules-icloud
                key: username
          - name: MAILRULES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mailrules-icloud
                key: password
        args:
          - --username=$(MAILRULES_USERNAME)
          - --password=$(MAILRULES_PASSWORD)
          - --host=imap.mail.me.com:993
          - --rules=/etc/mailrules/rules.txt
        volumeMounts:
          - name: rules
            mountPath: /etc/mailrules
          - name: journalclub
            mountPath: /usr/src/mailrules/journalclub
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: rules
          configMap:
            name: mailrules-rules
        - name: gcp-creds
          secret:
            secretName: gcp-creds
        - name: journalclub
          emptyDir: {}
